language: java
jdk:
- oraclejdk13
sudo: enabled
services:
  - mysql
before_install:
  - sudo mysql -e 'DROP DATABASE IF EXISTS bugsdb;'
  - sudo mysql -e 'CREATE DATABASE bugdb;'
  - sudo mysql < "db.sql"
script: mvn clean verify

 