language: java
jdk:
- oraclejdk13
sudo: disabled
services:
  - mysql
before_install:
  - sudo mysql -e 'DROP DATABASE IF EXISTS bugsdb;'
  - sudo mysql -e 'CREATE DATABASE bugdb;'
  - sudo mysql < "db2.0.sql"
script: mvn clean verify

